[package]
name = "AzureKeyVaultSignTool"
version = "0.1.0"
authors = ["Kevin Jones <kevin@vcsjones.com>"]
include = ["src/**/*"]
publish = false
license = "MIT"
build = "build.rs"

[dependencies]

[lib]
name = "akvst"
crate-type = ["dylib"]
